# Generated by Django 5.2 on 2025-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='성분명')),
                ('effect', models.TextField(verbose_name='효능')),
                ('side_effect', models.TextField(blank=True, verbose_name='부작용')),
                ('note', models.TextField(blank=True, verbose_name='특이사항')),
            ],
        ),
    ]
